/**
 * Человеческие имена монет для подписи под тикером. Биржи имён не отдают,
 * а тянуть их со стороннего API ради подписи — лишняя зависимость. Для
 * монет вне списка подпись просто не показывается.
 */
export const COIN_NAMES: Record<string, string> = {
  BTC: 'Bitcoin',
  ETH: 'Ethereum',
  SOL: 'Solana',
  XRP: 'Ripple',
  DOGE: 'Dogecoin',
  TON: 'Toncoin',
  AVAX: 'Avalanche',
  LINK: 'Chainlink',
  ARB: 'Arbitrum',
  OP: 'Optimism',
  SUI: 'Sui',
  APT: 'Aptos',
  INJ: 'Injective',
  SEI: 'Sei',
  TIA: 'Celestia',
  PEPE: 'Pepe',
  WIF: 'dogwifhat',
  BONK: 'Bonk',
  ORDI: 'Ordinals',
  JUP: 'Jupiter',
  PYTH: 'Pyth Network',
  RENDER: 'Render',
  FET: 'Fetch.ai',
  AAVE: 'Aave',
  LDO: 'Lido DAO',
  BNB: 'BNB',
  ADA: 'Cardano',
  DOT: 'Polkadot',
  POL: 'Polygon',
  LTC: 'Litecoin',
  BCH: 'Bitcoin Cash',
  NEAR: 'NEAR',
  ATOM: 'Cosmos',
  UNI: 'Uniswap',
  FIL: 'Filecoin',
  TRX: 'TRON',
  SHIB: 'Shiba Inu',
  ETC: 'Ethereum Classic',
  XLM: 'Stellar',
  HBAR: 'Hedera',
  ICP: 'Internet Computer',
  STX: 'Stacks',
  IMX: 'Immutable',
  GRT: 'The Graph',
  RUNE: 'THORChain',
  FTM: 'Fantom',
  ALGO: 'Algorand',
  VET: 'VeChain',
  ENA: 'Ethena',
  ONDO: 'Ondo',
  W: 'Wormhole',
  STRK: 'Starknet',
  ZK: 'ZKsync',
  TAO: 'Bittensor',
  KAS: 'Kaspa',
  TRUMP: 'Official Trump',
  HYPE: 'Hyperliquid',
  VIRTUAL: 'Virtuals',
};

export function coinName(base: string): string {
  return COIN_NAMES[base] ?? base;
}
